### ISSUE TITLE
Item Shop is broken - read desc

### ISSUE THREAD

**Issue by ShockMicro** [NucleoidMC/bed-wars#40] opened 2021-03-28 19:04 UTC
It allows you to buy blocks and switch tabs, but once you switch tabs, it does not let you buy or switch tabs. You can take out the item from the shop, but it is a ghost item and disappears on use.

**Comment by yitzy299** [comment] 2021-04-12 14:03
We discussed this on the discord: it appears to have been caused by #37

**Comment by Gegy** [comment] 2021-04-12 14:04
It is resolved in Plasmid with a band-aid fix, but the main issue now is https://github.com/arthurbambou/Server-Translations/issues/10

**Closed by Gegy** 2021-04-12 14:04 UTC
